export { default as AboutMe } from "./AboutMe"
export { default as ProjectPane } from "./ProjectPane"
export { default as NavBar } from "./NavBar"
export { default as Slide } from "./Slide"
export { default as Home } from "./Home"    